
version: "3.9"

services:
  lxde-vnc:
    build: .
    container_name: lxde-vnc

    # Map cổng VNC ra host
    ports:
      - "5900:5900"

    environment:
      VNC_PASSWORD: "docker" 
      VNC_GEOMETRY: "1360x768" 
      VNC_DEPTH: "24" 
      DISPLAY: ":99" 


    volumes:
      - ./data:/home/docker/data

    
    shm_size: "1g"

  
    restart: unless-stopped
